#!/usr/bin/env node

var Phant = require('../index'),
    dotenv = require('dotenv').load(),
    path = require('path'),
    Keychain = require('phant-keychain-hex'),
    Meta = require('phant-meta-nedb'),
    Storage = require('phant-stream-csv'),
    HttpManager = require('phant-manager-http'),
    app = Phant(),
    server_style = process.env.PHANT_SERVERSTYLE || 'http',
    http_port = process.env.PHANT_PORT || 8080,
    telnet_port = process.env.PHANT_TELNET_PORT || 8081;

console.log( "process.env.PHANT_SERVER_STLE = " + process.env.PHANT_SERVERSTYLE);

var keys = Keychain({
  publicSalt: process.env.PHANT_PUBLIC_SALT || 'public salt',
  privateSalt: process.env.PHANT_PRIVATE_SALT || 'private salt'
});

var meta = Meta({
  directory: process.env.PHANT_STORAGEDIR || 'phant_streams'
});

var stream = Storage({
  directory: process.env.PHANT_STORAGEDIR || 'phant_streams',
  cap: process.env.PHANT_CAP || 2 * 1024 * 1024 * 1024, // 2gb
  chunk: process.env.PHANT_CHUNK || 500 * 1024 // 500k
});

var validator = Phant.Validator({
  metadata: meta
});

var httpOutput = Phant.HttpOutput({
  validator: validator,
  storage: stream,
  keychain: keys
});

var httpInput = Phant.HttpInput({
  validator: validator,
  keychain: keys
});

// set up style of web server, http or https

var webserver = Phant.HttpServer;
if( server_style == 'https' ) {
    webserver = Phant.HttpsServer;
    Phant.HttpsServer.cert = process.env.PHANT_CERTFILE;
    Phant.HttpsServer.key = process.env.PHANT_KEYFILE;
  } 
// start listening for connections
webserver.listen(http_port);

var httpManager = HttpManager({
  metadata: meta,
  keychain: keys,
  validator: validator
});

// register manager with phant
app.registerManager(httpManager);

// attach manager to web server
webserver.use(httpManager);

// attach input to web server
webserver.use(httpInput);

// attach output to web server
webserver.use(httpOutput);

// register input with phant
app.registerInput(httpInput);

app.registerOutput(stream);
app.registerOutput(httpOutput);

// register telnet manager with phant
app.registerManager(
  Phant.TelnetManager({
    port: telnet_port,
    metadata: meta,
    keychain: keys,
    validator: validator
  })
);

console.log('phant ' + server_style + ' server running on port ' + http_port);
console.log('phant telnet server running on port ' + telnet_port);

